#!/usr/bin/env bash
set -Eeuo pipefail

# generate-pak7.sh — agrège des requirements de custom-nodes
# et produit un pak7.txt propre, non figé, sans doublons ni conflits.

echo "# Generated by generate-pak7.sh" > pak7.txt

# ────────────────────────────────────────────────────────────────────────────────
# Semences (packages que tu veux garder ici en priorité)
# ────────────────────────────────────────────────────────────────────────────────
cat >> pak7.txt << 'EOF'
facexlib
fvcore
gpytoolbox
EOF

# ────────────────────────────────────────────────────────────────────────────────
# Sources à agréger (requirements.txt en ligne)
# ────────────────────────────────────────────────────────────────────────────────
sources=(
  "https://github.com/akatz-ai/ComfyUI-AKatz-Nodes/raw/refs/heads/main/requirements.txt"
  "https://github.com/akatz-ai/ComfyUI-DepthCrafter-Nodes/raw/refs/heads/main/requirements.txt"
  "https://github.com/Amorano/Jovimetrix/raw/refs/heads/main/requirements.txt"
  "https://github.com/chflame163/ComfyUI_LayerStyle/raw/refs/heads/main/repair_dependency_list.txt"
  "https://github.com/chflame163/ComfyUI_LayerStyle/raw/refs/heads/main/requirements.txt"
  "https://github.com/city96/ComfyUI-GGUF/raw/refs/heads/main/requirements.txt"
  "https://github.com/digitaljohn/comfyui-propost/raw/refs/heads/master/requirements.txt"
  "https://github.com/Jonseed/ComfyUI-Detail-Daemon/raw/refs/heads/main/requirements.txt"
  "https://github.com/kijai/ComfyUI-DepthAnythingV2/raw/refs/heads/main/requirements.txt"
  "https://github.com/kijai/ComfyUI-Florence2/raw/refs/heads/main/requirements.txt"
  "https://github.com/mirabarukaso/ComfyUI_Mira/raw/refs/heads/main/requirements.txt"
  "https://github.com/nunchaku-tech/ComfyUI-nunchaku/raw/refs/heads/main/requirements.txt"
  "https://github.com/neverbiasu/ComfyUI-SAM2/raw/refs/heads/main/requirements.txt"
  "https://github.com/pydn/ComfyUI-to-Python-Extension/raw/refs/heads/main/requirements.txt"
  "https://github.com/yolain/ComfyUI-Easy-Use/raw/refs/heads/main/requirements.txt"
)

tmp_all="$(mktemp)"
trap 'rm -f -- "$tmp_all"' EXIT

# ────────────────────────────────────────────────────────────────────────────────
# Téléchargement & concaténation (tolérant aux échecs ponctuels)
# ────────────────────────────────────────────────────────────────────────────────
for url in "${sources[@]}"; do
  if curl -fsSL --retry 3 --retry-delay 1 "$url" >> "$tmp_all"; then
    printf '\n' >> "$tmp_all"
  else
    printf '[warn] download failed: %s\n' "$url" >&2
  fi
done

# ────────────────────────────────────────────────────────────────────────────────
# Normalisation :
#  - supprime commentaires/CRLF/espaces
#  - enlève markers après ';' (environnements)
#  - supprime tous les pins/comparateurs (==,>=,<=,~=,!=,<,>)
#  - conserve les extras [foo] (ex: qrcode[pil])
#  - remplace '_' par '-' (nom canonique PyPI) et met en minuscules
#  - NE modifie PAS les lignes git+
# ────────────────────────────────────────────────────────────────────────────────
tmp_norm="$(mktemp)"
trap 'rm -f -- "$tmp_all" "$tmp_norm"' EXIT

awk '
  BEGIN{ FS="\n"; OFS="\n"; }
  {
    gsub("\r","");                     # CRLF -> LF
    sub(/^[[:space:]]*#.*$/,"");       # commentaire pur
    sub(/[[:space:]]+#.*$/,"");        # commentaire en fin de ligne
    sub(/^[[:space:]]+/,"");           # trim left
    sub(/[[:space:]]+$/,"");           # trim right
    if ($0=="") next;

    split($0, parts, /[[:space:]]*;[[:space:]]*/); line=parts[1];  # coupe markers env

    if (line !~ /^git\+/) {
      # retire toutes les contraintes versionnelles (combinées ou non)
      gsub(/([[:space:]]*)(([<>=!~]=)[^,;[:space:]]+)([[:space:]]*,[[:space:]]*([<>=!~]=)[^,;[:space:]]+)*/,"", line);
      gsub(/[<>=!~]=/,"", line);       # comparateurs orphelins
      gsub(/_/,"-", line);             # nom canonique
      line=tolower(line);
      sub(/^[[:space:]]+/,"",line); sub(/[[:space:]]+$/,"",line);
    }
    print line;
  }
' "$tmp_all" > "$tmp_norm"

# ────────────────────────────────────────────────────────────────────────────────
# Filtrage :
#  - supprime paquets gérés ailleurs (torch/vision/audio, xformers, onnxruntime*, opencv*, numpy, cupy)
#  - supprime options pip (lignes commençant par --)
#  - supprime lignes vides
# ────────────────────────────────────────────────────────────────────────────────
tmp_filt="$(mktemp)"
trap 'rm -f -- "$tmp_all" "$tmp_norm" "$tmp_filt"' EXIT

grep -Eiv '^(#|--|pip[[:space:]]*:|torch($|[[:space:]\[]|-)|torchvision|torchaudio|xformers|onnxruntime(-gpu)?|opencv(-.*)?|opencv.*headless|^numpy($|[[:space:]]|\[)|^cupy($|-) )' \
  "$tmp_norm" \
  | sed '/^[[:space:]]*$/d' \
  >> pak7.txt

# ────────────────────────────────────────────────────────────────────────────────
# Déduplication & retrait des doublons inter-packs (pak4/pak5/pak6/pak8 si présents)
# ────────────────────────────────────────────────────────────────────────────────
# On sépare git+ et PyPI pour un tri propre
tmp_current="$(mktemp)"; git_lines="$(mktemp)"; pypi_lines="$(mktemp)"
trap 'rm -f -- "$tmp_all" "$tmp_norm" "$tmp_filt" "$tmp_current" "$git_lines" "$pypi_lines"' EXIT

# contenu actuel (avec semences + ajouts filtrés)
cat pak7.txt > "$tmp_current"

grep -E '^git\+' "$tmp_current" | awk '!seen[$0]++' > "$git_lines" || true
grep -Ev '^git\+' "$tmp_current" | sort -fu > "$pypi_lines" || true

# retire ce qui existe déjà dans pak4/pak5/pak6/pak8
tmp_merge="$(mktemp)"
trap 'rm -f -- "$tmp_all" "$tmp_norm" "$tmp_filt" "$tmp_current" "$git_lines" "$pypi_lines" "$tmp_merge"' EXIT
cat "$pypi_lines" > "$tmp_merge"

for other in pak4.txt pak5.txt pak6.txt pak8.txt; do
  if [[ -f "$other" ]]; then
    grep -Fixv -f <(grep -Ev '^git\+' "$other" || true) "$tmp_merge" > "${tmp_merge}.new" || true
    mv "${tmp_merge}.new" "$tmp_merge"
  fi
done

# ────────────────────────────────────────────────────────────────────────────────
# Écriture finale
# ────────────────────────────────────────────────────────────────────────────────
{
  echo "# pak7.txt — auto-généré (non figé). Vérifie avant usage."
  cat "$tmp_merge"
  echo
  cat "$git_lines"
} > pak7.txt

echo "<pak7.txt> generated. Check before use."
