#!/usr/bin/env bash
set -Eeuo pipefail

# generate-pak5.sh — agrège les requirements de plusieurs custom-nodes
# et produit un pak5.txt propre, non figé, sans doublons ni conflits.

echo "# Generated by generate-pak5.sh" > pak5.txt

# ────────────────────────────────────────────────────────────────────────────────
# Sources à agréger (requirements.txt en ligne)
# Ajoute/retire librement, l'ordre n'a pas d'importance.
# ────────────────────────────────────────────────────────────────────────────────
sources=(
  "https://github.com/comfyanonymous/ComfyUI/raw/refs/heads/master/requirements.txt"
  "https://github.com/Comfy-Org/ComfyUI-Manager/raw/refs/heads/main/requirements.txt"
  "https://github.com/crystian/ComfyUI-Crystools/raw/refs/heads/main/requirements.txt"
  "https://github.com/cubiq/ComfyUI_essentials/raw/refs/heads/main/requirements.txt"
  "https://github.com/cubiq/ComfyUI_FaceAnalysis/raw/refs/heads/main/requirements.txt"
  "https://github.com/cubiq/ComfyUI_InstantID/raw/refs/heads/main/requirements.txt"
  "https://github.com/cubiq/PuLID_ComfyUI/raw/refs/heads/main/requirements.txt"
  "https://github.com/Fannovel16/comfyui_controlnet_aux/raw/refs/heads/main/requirements.txt"
  "https://github.com/Fannovel16/ComfyUI-Frame-Interpolation/raw/refs/heads/main/requirements-no-cupy.txt"
  "https://github.com/FizzleDorf/ComfyUI_FizzNodes/raw/refs/heads/main/requirements.txt"
  "https://github.com/Gourieff/ComfyUI-ReActor/raw/refs/heads/main/requirements.txt"
  "https://github.com/huchenlei/ComfyUI-layerdiffuse/raw/refs/heads/main/requirements.txt"
  "https://github.com/jags111/efficiency-nodes-comfyui/raw/refs/heads/main/requirements.txt"
  "https://github.com/kijai/ComfyUI-KJNodes/raw/refs/heads/main/requirements.txt"
  "https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/raw/refs/heads/main/requirements.txt"
  "https://github.com/ltdrdata/ComfyUI-Impact-Pack/raw/refs/heads/Main/requirements.txt"
  "https://github.com/ltdrdata/ComfyUI-Impact-Subpack/raw/refs/heads/main/requirements.txt"
  "https://github.com/ltdrdata/ComfyUI-Inspire-Pack/raw/refs/heads/main/requirements.txt"
  "https://github.com/melMass/comfy_mtb/raw/refs/heads/main/requirements.txt"
  "https://github.com/ltdrdata/was-node-suite-comfyui/raw/refs/heads/main/requirements.txt"
)

tmp_all="$(mktemp)"
trap 'rm -f -- "$tmp_all"' EXIT

# ────────────────────────────────────────────────────────────────────────────────
# Téléchargement & concaténation (tolérant aux échecs ponctuels)
# ────────────────────────────────────────────────────────────────────────────────
for url in "${sources[@]}"; do
  if curl -fsSL --retry 3 --retry-delay 1 "$url" >> "$tmp_all"; then
    printf '\n' >> "$tmp_all"
  else
    printf '[warn] download failed: %s\n' "$url" >&2
  fi
done

# ────────────────────────────────────────────────────────────────────────────────
# Normalisation :
#  - supprime commentaires/CRLF/espaces
#  - enlève markers après ';' (environnements)
#  - supprime tous les pins/comparateurs (==,>=,<=,~=,!=,<,>)
#  - conserve les extras [foo] (ex: qrcode[pil])
#  - remplace '_' par '-' (nom canonique PyPI)
#  - met en minuscules les lignes non-URL (git+ conserve la casse)
# ────────────────────────────────────────────────────────────────────────────────
tmp_norm="$(mktemp)"
trap 'rm -f -- "$tmp_all" "$tmp_norm"' EXIT

awk '
  BEGIN{ FS="\n"; OFS="\n"; }
  {
    gsub("\r","");                     # CRLF -> LF
    sub(/^[[:space:]]*#.*$/,"");       # ligne commentaire pure
    sub(/[[:space:]]+#.*$/,"");        # trailing comment
    sub(/^[[:space:]]+/,"");           # trim left
    sub(/[[:space:]]+$/,"");           # trim right
    if ($0=="") next;

    # couper les environment markers ; prio à la partie gauche
    split($0, parts, /[[:space:]]*;[[:space:]]*/); line=parts[1];

    # on normalise seulement si ce n est pas une URL git+
    if (line !~ /^git\+/) {
      # retirer toutes les contraintes versionnelles (combinées ou non)
      # exemples: pkg==1.2.3, pkg>=1.0,<2 ; pkg~=2.7.0 ; pkg!=1.0
      gsub(/([[:space:]]*)(([<>=!~]=)[^,;[:space:]]+)([[:space:]]*,[[:space:]]*([<>=!~]=)[^,;[:space:]]+)*/,"", line);
      # retirer éventuels comparateurs orphelins
      gsub(/[<>=!~]=/,"", line);
      # normaliser underscores -> dashes dans le nom de package
      gsub(/_/,"-", line);
      # minuscules
      line=tolower(line);
      # re-trim
      sub(/^[[:space:]]+/,"",line); sub(/[[:space:]]+$/,"",line);
    }
    print line;
  }
' "$tmp_all" > "$tmp_norm"

# ────────────────────────────────────────────────────────────────────────────────
# Filtrage :
#  - supprime paquets gérés ailleurs (torch/xformers/onnx/opencv/numpy/cupy…)
#  - supprime lignes vides & options pip
# ────────────────────────────────────────────────────────────────────────────────
tmp_filt="$(mktemp)"
trap 'rm -f -- "$tmp_all" "$tmp_norm" "$tmp_filt"' EXIT

grep -Eiv '^(#|--|pip[[:space:]]*:|torch($|[[:space:]\[]|-)|torchvision|torchaudio|xformers|onnxruntime(-gpu)?|opencv(-.*)?|opencv.*headless|^numpy($|[[:space:]]|\[)|^cupy($|-) )' \
  "$tmp_norm" \
  | sed '/^[[:space:]]*$/d' \
  > "$tmp_filt"

# ────────────────────────────────────────────────────────────────────────────────
# Déduplication et tri (en conservant git+ tel quel)
# ────────────────────────────────────────────────────────────────────────────────
# On sépare git+ et PyPI pour dédupliquer/ordonner proprement.
git_lines="$(mktemp)"; pypi_lines="$(mktemp)"
trap 'rm -f -- "$tmp_all" "$tmp_norm" "$tmp_filt" "$git_lines" "$pypi_lines"' EXIT

grep -E '^git\+' "$tmp_filt" | awk '!seen[$0]++' > "$git_lines" || true
grep -Ev '^git\+' "$tmp_filt" | sort -fu > "$pypi_lines" || true

# ────────────────────────────────────────────────────────────────────────────────
# Retire les doublons déjà listés dans d autres paquets (pak4/6/7/8) s ils existent.
# ────────────────────────────────────────────────────────────────────────────────
tmp_merge="$(mktemp)"
trap 'rm -f -- "$tmp_all" "$tmp_norm" "$tmp_filt" "$git_lines" "$pypi_lines" "$tmp_merge"' EXIT

cat "$pypi_lines" > "$tmp_merge"
for other in pak4.txt pak6.txt pak7.txt pak8.txt; do
  if [[ -f "$other" ]]; then
    # compare uniquement les lignes PyPI (hors git+)
    grep -Fixv -f <(grep -Ev '^git\+' "$other" || true) "$tmp_merge" > "${tmp_merge}.new" || true
    mv "${tmp_merge}.new" "$tmp_merge"
  fi
done

# ────────────────────────────────────────────────────────────────────────────────
# Écriture finale
# ────────────────────────────────────────────────────────────────────────────────
{
  echo "# pak5.txt — auto-généré (non figé). Vérifie avant usage."
  cat "$tmp_merge"
  echo
  # les lignes git+ à la fin (non triées pour garder l ordre source)
  cat "$git_lines"
} >> pak5.txt

echo "<pak5.txt> generated. Check before use."
